CREATE TABLE MOVIE2DIRECTOR (moviesDirected_ID INTEGER NOT NULL, directors_ID INTEGER NOT NULL, PRIMARY KEY (moviesDirected_ID, directors_ID));
ALTER TABLE MOVIE2DIRECTOR ADD CONSTRAINT FK_MOVIE2DIRECTOR_moviesDirected_ID FOREIGN KEY (moviesDirected_ID) REFERENCES MOVIE (ID);
ALTER TABLE MOVIE2DIRECTOR ADD CONSTRAINT FK_MOVIE2DIRECTOR_directors_ID FOREIGN KEY (directors_ID) REFERENCES PERSON (ID);
