CREATE TABLE MOVIE (ID INTEGER AUTO_INCREMENT NOT NULL, TITLE VARCHAR(255), LIBRARY_ID INTEGER, PRIMARY KEY (ID));
ALTER TABLE MOVIE ADD CONSTRAINT FK_MOVIE_LIBRARY_ID FOREIGN KEY (LIBRARY_ID) REFERENCES MOVIELIBRARY (ID);
